title: Visual Studio Geeks
description: "24x7 Visual Studio Geeks"
analytics: UA-57919718-1 #Google analytics code in the format XX-nnnnnnnn-n

url: http://www.visualstudiogeeks.com
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  
permalink: /:categories/:title
markdown: kramdown

google_analytics: UA-57919718-1

owner:
  name: Utkarsh Shigihalli & Tarun Arora
  disqus_shortname: visualstudiogeeks

  
 